// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function SetDefaultProfile(arg1) {
  return window['go']['main']['App']['SetDefaultProfile'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
