// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {importer} from '../models';
import {committer} from '../models';
import {profile} from '../models';
import {main} from '../models';
import {settings} from '../models';
import {issuerepo} from '../models';
import {journal} from '../models';
import {importfile} from '../models';
import {syncer} from '../models';

export function AddLink(arg1:string,arg2:string,arg3:backend.LinkDraft):Promise<void>;

export function AutoMapImport(arg1:Array<string>):Promise<importer.Mapping>;

export function CommitPendingChanges(arg1:string):Promise<committer.Result>;

export function CreateIssue(arg1:string,arg2:backend.IssueDraft):Promise<string>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<profile.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DiscardAllPendingChanges(arg1:string):Promise<number>;

export function DiscardPendingChange(arg1:string,arg2:number):Promise<void>;

export function EditIssue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetCreateFields(arg1:string,arg2:string):Promise<Array<backend.FieldSpec>>;

export function GetDiagnostics():Promise<main.Diagnostics>;

export function GetIssueDetail(arg1:string,arg2:string):Promise<backend.IssueDetail>;

export function GetLinkTypes(arg1:string):Promise<Array<backend.LinkType>>;

export function GetProfileSetting(arg1:string,arg2:string):Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetSyncState(arg1:string):Promise<issuerepo.SyncState>;

export function Health():Promise<main.HealthInfo>;

export function ImportIssues(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:importer.Mapping,arg6:boolean):Promise<importer.Result>;

export function ListActivity(arg1:string,arg2:string,arg3:number):Promise<Array<journal.AuditEntry>>;

export function ListIssues(arg1:string,arg2:issuerepo.IssueQuery):Promise<issuerepo.IssuePage>;

export function ListLinkedTests(arg1:string,arg2:string):Promise<Array<issuerepo.LinkedTest>>;

export function ListPendingChanges(arg1:string):Promise<Array<journal.PendingChange>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListSprints(arg1:string):Promise<Array<issuerepo.SprintRef>>;

export function LookupIssue(arg1:string,arg2:string):Promise<backend.Issue>;

export function PreviewImport(arg1:string,arg2:boolean):Promise<importfile.Preview>;

export function ResolveConflictKeepRemote(arg1:string,arg2:string):Promise<void>;

export function ResolveConflictOverride(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveImportTemplate():Promise<string>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SetProfileSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SyncIssues(arg1:string,arg2:boolean):Promise<syncer.Summary>;
