// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddLink'](arg1, arg2, arg3);
}

export function AutoMapImport(arg1) {
  return window['go']['main']['App']['AutoMapImport'](arg1);
}

export function CanTransition(arg1, arg2, arg3) {
  return window['go']['main']['App']['CanTransition'](arg1, arg2, arg3);
}

export function CommitPendingChanges(arg1) {
  return window['go']['main']['App']['CommitPendingChanges'](arg1);
}

export function CompleteSprint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompleteSprint'](arg1, arg2, arg3, arg4);
}

export function CreateIssue(arg1, arg2) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2);
}

export function CreateProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateProfileReusingToken(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProfileReusingToken'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSprint(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateSprint'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSprint(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSprint'](arg1, arg2, arg3);
}

export function DiscardAllPendingChanges(arg1) {
  return window['go']['main']['App']['DiscardAllPendingChanges'](arg1);
}

export function DiscardPendingChange(arg1, arg2) {
  return window['go']['main']['App']['DiscardPendingChange'](arg1, arg2);
}

export function EditIssue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditIssue'](arg1, arg2, arg3, arg4);
}

export function EditSprint(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['EditSprint'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function GetBoard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetBoard'](arg1, arg2, arg3, arg4);
}

export function GetCreateFields(arg1, arg2) {
  return window['go']['main']['App']['GetCreateFields'](arg1, arg2);
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetEpicTree(arg1, arg2) {
  return window['go']['main']['App']['GetEpicTree'](arg1, arg2);
}

export function GetIssueDetail(arg1, arg2) {
  return window['go']['main']['App']['GetIssueDetail'](arg1, arg2);
}

export function GetLinkTypes(arg1) {
  return window['go']['main']['App']['GetLinkTypes'](arg1);
}

export function GetProfileSetting(arg1, arg2) {
  return window['go']['main']['App']['GetProfileSetting'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubtaskTypeName(arg1) {
  return window['go']['main']['App']['GetSubtaskTypeName'](arg1);
}

export function GetSyncState(arg1) {
  return window['go']['main']['App']['GetSyncState'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ImportIssues(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ImportIssues'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function JournalSprintMoves(arg1, arg2, arg3) {
  return window['go']['main']['App']['JournalSprintMoves'](arg1, arg2, arg3);
}

export function ListActivity(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListActivity'](arg1, arg2, arg3);
}

export function ListBoardSprintDetails(arg1, arg2) {
  return window['go']['main']['App']['ListBoardSprintDetails'](arg1, arg2);
}

export function ListBoardSprints(arg1, arg2) {
  return window['go']['main']['App']['ListBoardSprints'](arg1, arg2);
}

export function ListBoards(arg1) {
  return window['go']['main']['App']['ListBoards'](arg1);
}

export function ListEpics(arg1) {
  return window['go']['main']['App']['ListEpics'](arg1);
}

export function ListIssues(arg1, arg2) {
  return window['go']['main']['App']['ListIssues'](arg1, arg2);
}

export function ListLinkedTests(arg1, arg2) {
  return window['go']['main']['App']['ListLinkedTests'](arg1, arg2);
}

export function ListOpenSprints(arg1) {
  return window['go']['main']['App']['ListOpenSprints'](arg1);
}

export function ListPendingChanges(arg1) {
  return window['go']['main']['App']['ListPendingChanges'](arg1);
}

export function ListPriorities(arg1) {
  return window['go']['main']['App']['ListPriorities'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListSprints(arg1) {
  return window['go']['main']['App']['ListSprints'](arg1);
}

export function LookupIssue(arg1, arg2) {
  return window['go']['main']['App']['LookupIssue'](arg1, arg2);
}

export function MoveIssueToColumn(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveIssueToColumn'](arg1, arg2, arg3);
}

export function MoveIssueToSprint(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveIssueToSprint'](arg1, arg2, arg3);
}

export function PendingInSprint(arg1, arg2) {
  return window['go']['main']['App']['PendingInSprint'](arg1, arg2);
}

export function PreviewImport(arg1, arg2) {
  return window['go']['main']['App']['PreviewImport'](arg1, arg2);
}

export function RankIssue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RankIssue'](arg1, arg2, arg3, arg4, arg5);
}

export function ResolveConflictKeepRemote(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflictKeepRemote'](arg1, arg2);
}

export function ResolveConflictOverride(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflictOverride'](arg1, arg2, arg3);
}

export function SaveImportTemplate(arg1) {
  return window['go']['main']['App']['SaveImportTemplate'](arg1);
}

export function SearchUsers(arg1, arg2) {
  return window['go']['main']['App']['SearchUsers'](arg1, arg2);
}

export function SetDefaultProfile(arg1) {
  return window['go']['main']['App']['SetDefaultProfile'](arg1);
}

export function SetNavRailVisible(arg1) {
  return window['go']['main']['App']['SetNavRailVisible'](arg1);
}

export function SetProfileSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProfileSetting'](arg1, arg2, arg3);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartSprint(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartSprint'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SuggestSprintDates(arg1, arg2) {
  return window['go']['main']['App']['SuggestSprintDates'](arg1, arg2);
}

export function SyncBoards(arg1) {
  return window['go']['main']['App']['SyncBoards'](arg1);
}

export function SyncIssues(arg1, arg2) {
  return window['go']['main']['App']['SyncIssues'](arg1, arg2);
}

export function TestConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3, arg4);
}

export function TestProfileConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestProfileConnection'](arg1, arg2, arg3, arg4);
}

export function UpdateProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
