// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {importer} from '../models';
import {committer} from '../models';
import {sprints} from '../models';
import {profile} from '../models';
import {main} from '../models';
import {boardrepo} from '../models';
import {issuerepo} from '../models';
import {settings} from '../models';
import {sprintreport} from '../models';
import {journal} from '../models';
import {importfile} from '../models';
import {syncer} from '../models';

export function AddLink(arg1:string,arg2:string,arg3:backend.LinkDraft):Promise<void>;

export function AutoMapImport(arg1:Array<string>):Promise<importer.Mapping>;

export function CanTransition(arg1:string,arg2:string,arg3:string):Promise<backend.TransitionCheck>;

export function CancelSprintReport(arg1:string):Promise<void>;

export function CommitPendingChanges(arg1:string):Promise<committer.Result>;

export function CompleteSprint(arg1:string,arg2:number,arg3:number,arg4:string):Promise<sprints.Completion>;

export function CreateIssue(arg1:string,arg2:backend.IssueDraft):Promise<string>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<profile.Profile>;

export function CreateProfileReusingToken(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<profile.Profile>;

export function CreateSprint(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.SprintCreated>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSprint(arg1:string,arg2:number,arg3:number):Promise<string>;

export function DiscardAllPendingChanges(arg1:string):Promise<number>;

export function DiscardPendingChange(arg1:string,arg2:number):Promise<void>;

export function EditIssue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditSprint(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<string>;

export function ExportProfile(arg1:string):Promise<string>;

export function GetBoard(arg1:string,arg2:number,arg3:string,arg4:string):Promise<boardrepo.BoardView>;

export function GetCreateFields(arg1:string,arg2:string):Promise<Array<backend.FieldSpec>>;

export function GetDiagnostics():Promise<main.Diagnostics>;

export function GetEpicTree(arg1:string,arg2:issuerepo.TreeQuery):Promise<issuerepo.Tree>;

export function GetIssueDetail(arg1:string,arg2:string):Promise<backend.IssueDetail>;

export function GetLinkTypes(arg1:string):Promise<Array<backend.LinkType>>;

export function GetProfileSetting(arg1:string,arg2:string):Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetSprintReport(arg1:string,arg2:number,arg3:number):Promise<sprintreport.Report>;

export function GetSubtaskTypeName(arg1:string):Promise<string>;

export function GetSyncState(arg1:string):Promise<issuerepo.SyncState>;

export function Health():Promise<main.HealthInfo>;

export function ImportIssues(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:importer.Mapping,arg6:boolean):Promise<importer.Result>;

export function ImportProfile():Promise<profile.Profile>;

export function JournalSprintMoves(arg1:string,arg2:Array<string>,arg3:string):Promise<number>;

export function ListActivity(arg1:string,arg2:string,arg3:number):Promise<Array<journal.AuditEntry>>;

export function ListBoardSprintDetails(arg1:string,arg2:number):Promise<Array<boardrepo.SprintDetail>>;

export function ListBoardSprints(arg1:string,arg2:number):Promise<Array<boardrepo.Sprint>>;

export function ListBoards(arg1:string):Promise<Array<boardrepo.Board>>;

export function ListEpics(arg1:string):Promise<Array<backend.Issue>>;

export function ListIssues(arg1:string,arg2:issuerepo.IssueQuery):Promise<issuerepo.IssuePage>;

export function ListLinkedTests(arg1:string,arg2:string):Promise<Array<issuerepo.LinkedTest>>;

export function ListOpenSprints(arg1:string):Promise<Array<boardrepo.SprintChoice>>;

export function ListPendingChanges(arg1:string):Promise<Array<journal.PendingChange>>;

export function ListPriorities(arg1:string):Promise<Array<string>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListSprints(arg1:string):Promise<Array<issuerepo.SprintRef>>;

export function LookupIssue(arg1:string,arg2:string):Promise<backend.Issue>;

export function MoveIssueToColumn(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveIssueToSprint(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PendingInSprint(arg1:string,arg2:number):Promise<number>;

export function PreviewImport(arg1:string,arg2:boolean):Promise<importfile.Preview>;

export function RankIssue(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<void>;

export function ResolveConflictKeepRemote(arg1:string,arg2:string):Promise<void>;

export function ResolveConflictOverride(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveImportTemplate(arg1:string):Promise<string>;

export function SearchUsers(arg1:string,arg2:string):Promise<Array<backend.User>>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SetNavRailVisible(arg1:boolean):Promise<void>;

export function SetProfileSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartSprint(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function SuggestSprintDates(arg1:string,arg2:number):Promise<sprints.Suggestion>;

export function SyncBoards(arg1:string):Promise<syncer.BoardSummary>;

export function SyncIssues(arg1:string,arg2:boolean):Promise<syncer.Summary>;

export function TestConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function TestProfileConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<profile.Profile>;
