// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';
import {main} from '../models';
import {settings} from '../models';

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<profile.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetDiagnostics():Promise<main.Diagnostics>;

export function GetSettings():Promise<settings.Settings>;

export function Health():Promise<main.HealthInfo>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
