// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetSyncState(arg1) {
  return window['go']['main']['App']['GetSyncState'](arg1);
}

export function GetTest(arg1, arg2) {
  return window['go']['main']['App']['GetTest'](arg1, arg2);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListTests(arg1, arg2) {
  return window['go']['main']['App']['ListTests'](arg1, arg2);
}

export function SyncProfile(arg1) {
  return window['go']['main']['App']['SyncProfile'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
