// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';
import {testrepo} from '../models';

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<profile.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetSyncState(arg1:string):Promise<testrepo.SyncState>;

export function GetTest(arg1:string,arg2:string):Promise<testrepo.TestCase>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListTests(arg1:string,arg2:testrepo.Query):Promise<testrepo.Page>;

export function SyncProfile(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<string>;
