// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkEditTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkEditTests'](arg1, arg2, arg3);
}

export function CommitPendingChanges(arg1) {
  return window['go']['main']['App']['CommitPendingChanges'](arg1);
}

export function CreateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DiscardPendingChange(arg1, arg2) {
  return window['go']['main']['App']['DiscardPendingChange'](arg1, arg2);
}

export function EditTestField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditTestField'](arg1, arg2, arg3, arg4);
}

export function GetSyncState(arg1) {
  return window['go']['main']['App']['GetSyncState'](arg1);
}

export function GetTest(arg1, arg2) {
  return window['go']['main']['App']['GetTest'](arg1, arg2);
}

export function GetTestPreconditions(arg1, arg2) {
  return window['go']['main']['App']['GetTestPreconditions'](arg1, arg2);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListAuditEntries(arg1, arg2) {
  return window['go']['main']['App']['ListAuditEntries'](arg1, arg2);
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListPendingChanges(arg1) {
  return window['go']['main']['App']['ListPendingChanges'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListTests(arg1, arg2) {
  return window['go']['main']['App']['ListTests'](arg1, arg2);
}

export function SyncProfile(arg1) {
  return window['go']['main']['App']['SyncProfile'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}
