// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {testrepo} from '../models';
import {main} from '../models';
import {syncer} from '../models';
import {profile} from '../models';
import {jira} from '../models';

export function AddTestStep(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<testrepo.Step>;

export function AllocateTests(arg1:string,arg2:string,arg3:Array<string>):Promise<testrepo.AllocateResult>;

export function BulkEditTests(arg1:string,arg2:Array<string>,arg3:testrepo.BulkEdit):Promise<testrepo.BulkEditResult>;

export function BulkMoveToFolder(arg1:string,arg2:Array<string>,arg3:string):Promise<testrepo.BulkEditResult>;

export function BulkTransitionTests(arg1:string,arg2:Array<string>,arg3:string):Promise<main.BulkTransitionResult>;

export function CommitPendingChanges(arg1:string):Promise<syncer.CommitResult>;

export function CreateContainerAndAllocate(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<testrepo.CreateContainerResult>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<profile.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteTestStep(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DiscardPendingChange(arg1:string,arg2:number):Promise<void>;

export function EditTestField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditTestStepField(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function GetBulkTransitionOptions(arg1:string,arg2:Array<string>):Promise<main.BulkTransitionOptions>;

export function GetStatistics(arg1:string):Promise<testrepo.Statistics>;

export function GetSyncState(arg1:string):Promise<testrepo.SyncState>;

export function GetTest(arg1:string,arg2:string):Promise<testrepo.TestCase>;

export function GetTestContainers(arg1:string,arg2:string):Promise<Array<testrepo.ContainerMembership>>;

export function GetTestPlanBoard(arg1:string,arg2:string):Promise<testrepo.TestPlanBoard>;

export function GetTestPreconditions(arg1:string,arg2:string):Promise<Array<testrepo.Precondition>>;

export function GetTestSteps(arg1:string,arg2:string,arg3:boolean):Promise<Array<testrepo.Step>>;

export function GetTestTransitions(arg1:string,arg2:string):Promise<Array<jira.Transition>>;

export function Health():Promise<main.HealthInfo>;

export function ListAuditEntries(arg1:string,arg2:number):Promise<Array<testrepo.AuditEntry>>;

export function ListContainers(arg1:string,arg2:string):Promise<Array<testrepo.Container>>;

export function ListFolders(arg1:string):Promise<Array<testrepo.Folder>>;

export function ListMatchingKeys(arg1:string,arg2:testrepo.Query):Promise<Array<string>>;

export function ListPendingChanges(arg1:string):Promise<Array<testrepo.PendingChange>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListTests(arg1:string,arg2:testrepo.Query):Promise<testrepo.Page>;

export function MoveTestToFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderTestSteps(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SeedSampleContainers(arg1:string):Promise<testrepo.SeedResult>;

export function SyncProfile(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<string>;

export function TransitionTest(arg1:string,arg2:string,arg3:string):Promise<void>;
